fastlane_version "1.95.0"

default_platform :ios

platform :ios do
  before_all do
    # ENV["SLACK_URL"] = "https://hooks.slack.com/services/..."
    cocoapods
  end

  desc "Runs all the tests"
  lane :test do
    scan(scheme: "Footbl Development")
  end

  desc "Submit a new Beta Build to HockeyApp"
  lane :beta do
    gym(scheme: "Footbl Beta")

    hockey(
      api_token: '...',
      ipa: './app.ipa',
      notes: "Changelog"
    )
  end

  desc "Deploy a new version to the App Store"
  lane :appstore do
    gym(scheme: "Footbl")
    deliver(force: true)
  end

  # You can define as many lanes as you want

  after_all do |lane|
    # This block is called, only if the executed lane was successful

    # slack(
    #   message: "Successfully deployed new App Update."
    # )
  end

  error do |lane, exception|
    # slack(
    #   message: exception.message,
    #   success: false
    # )
  end
end
